### ISSUE TITLE
Angular tries to collect metadata from onEnter but fails at missing prototype

### ISSUE THREAD

**Issue by TitanNano** [ui-router/angular#145]
I defined a state like this:

```JavaScript
let TestState = { 
    name: 'state', 
    url: '/state', 
    onEnter(trans, state) { 
        alert(state) 
    }
};
```
The problem is that all states are handed to the angular jit compiler. The compiler then tries to collect metadata objects for all components and appears to also pickup the onEnter method.
Since shorthand method definitions do not have a prototype the metadata collection and angular crashes.

I'm not sure who should handle this, but I asume that it shouldn't be handed to the compiler in the first place.

Plunker: https://plnkr.co/edit/emMpITE71x5kYrXmZ5Vw?p=preview

**Comment by christopherthielen** [comment]
Any states that are registered using DI must be processed by the compiler. 

If you want to register states outside of the DI system (a very reasonable idea) you can do that (for example) using a config function: https://plnkr.co/edit/eRTNAE?p=preview

Closing because I don't think there's much we can do about Angular's compiler and there's an easy workaround if it's a problem
