### ISSUE TITLE
cannot find any index in '@uirouter/angular'

### ISSUE THREAD

**Issue by kirakishin** [ui-router/angular#157]
Hello,

i use the beta 7 and i am facing to a painful problem.
I use it inside my lib generated by yeoman-angular2-library,
and in my consuming app.

when i build with `ng build --prod`, error that can't find '@uirouter/angular/index' is here.
Should your root folder may has an index.d.ts and index.js , no ?

anyone uses uirouter in an angular 4 library ?

```bash
        using description file: C:\git\itsm\ops-webapp\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\git\itsm\ops-webapp\package.json (relative path: ./src)
          using description file: C:\git\itsm\ops-webapp\package.json (relative path: ./src/@uirouter/angular/index)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\git\itsm\ops-webapp\src\@uirouter\angular\index doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\git\itsm\ops-webapp\src\@uirouter\angular\index.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\git\itsm\ops-webapp\src\@uirouter\angular\index.js doesn't exist
            as directory
              C:\git\itsm\ops-webapp\src\@uirouter\angular\index doesn't exist

```

regards

**Comment by rob-gijsens** [comment]
Hi,

I'm having the exact same error. In my case I'm building a library based on [angular-library-starter](https://github.com/robisim74/angular-library-starter). The library i'm building also depends on the 1.0.0-beta.7 version of ``@uirouter/angular``. In my case the error also occurs when i try to serve/build an Angular application which uses my library.

After a little research I observed the following:
When I try to build my library it seems to be all okay. But when I search through the compiled javascript files in my ``/dist`` directory I can see that every import from the ``@uirouter/angular`` package done in my library typescript files is rewritten in the compiled javascript file to one import from ``@uirouter/angular/index``.

**For example:**

_Typescript file A:_
``import {UIRouterModule} from '@angular/uirouter';``

_Typescript file B:_
``import {UIRouter} from '@angular/uirouter';``

**results in the compiled javascript file to:**

``import { UIRouter, UIRouterModule } from '@uirouter/angular/index';``

Is this behaviour caused by a certain compile option? Because when I start a fresh Angular application without my own library but with ``@uirouter/angular`` as a direct dependecy and build this boilerplate project, I can't detect the same behavior in the ``/dist`` directory.

Hope that someone can help with this.

**Comment by christopherthielen** [comment]
this is a bug in `angular-cli` which is recently fixed: https://github.com/angular/angular/issues/17171
