### ISSUE TITLE
Blank Page when using aot

### ISSUE THREAD

**Issue by jensengar** [ui-router/angular#218]
I'm not sure where to go with this, but when I use `ng serve --aot` I see the loading, then just a blank page. Everything works fine without the `--aot` flag. I have verified that the config for the UIRouter module is running, but no states ever get triggered (I have some transition hooks that never activate when use aot). I have no errors in js console or in terminal. Any ideas?

angular 5.2.4
uirouter 1.0.0

**Comment by christopherthielen** [comment]
It is difficult to diagnose with the information provided.  Are you able to reproduce it using the [sample app](https://github.com/ui-router/sample-app-angular)?  

Here are some other tips:

- Add the ui-router-visualizer (`router.plugin(Visualizer)` with `import { Visualizer } from '@uirouter/visualizer'`)
- Enable tracing in your config (`router.trace.enable()`)
- Verify that the states are getting registered (`setTimeout(() => console.log(router.stateRegistry.get()), 1000)`)
- Add an "otherwise" rule to see if the router started, but no rules matched (`router.urlService.rules.otherwise(() => console.log('no url matched'))`)
