### ISSUE TITLE
PolicyAsync: NOWAIT is not providing promise for injected values

### ISSUE THREAD

**Issue by GabrielAlquimia** [ui-router/angular#232]
When I use the NOWAIT policy for a resolve I expect any value wrapped in a promise as the [docs](https://ui-router.github.io/ng2/docs/latest/interfaces/resolve.resolvepolicy.html) say. 

However I am receiving undefined if a promise is returned from the resolve or the value itself if the resolve returns a string.

I [forked the sample app](https://stackblitz.com/edit/github-xjifmf) to demonstrate this. I updated the ui-router version to 1.0.1, the state world now defines two resolves (one that returns a promise and one that returns a string with the NOWAIT policy) and the WorldComponent prints them on ngOnInit and binds them to the template. 

In the template and in the console you can see that the resolved promise is undefined and the resolved string has the value itself and it's not wrapped in a promise.

**Comment by christopherthielen** [comment]
Thanks! I see the problem and hope to get a fix out shortly.

**Comment by avBerenger** [comment]
I've encounter a weird behavior about that fix.

Indeed, now, a resolve's promise is set to the matching `@Input()` of the component. But not in all cases.

If I had to guess, I would say that fast promises are properly set to the component (and contains the right value), however slow promises are not given to the component event if the resolve is correctly executed and the http request is made. 

NB : if I use Observable instead of Promise, `@Input()` are correctly set for all cases but, they doesn't contains the right value (seems to be nested observables instead).
