### ISSUE TITLE
ParamType not compatible with Angular AOT

### ISSUE THREAD

**Issue by jonrimmer** [ui-router/angular#249]
Trying to use `ParamType` in a route definition that is compiled using AOT fails:

E.g.:

```js
import { ParamTypes } from '@uirouter/core';

  {
    name: 'world.nest', 
    url: '/nest/:id',
    component: NestComponent ,
    params: {
      id: {
        type: ParamTypes.string,
        raw: true,
        value: null
      }
    }
  }
```

Gives:

```
ERROR in Error during template compile of 'AppModule'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'ParamTypes'
    'ParamTypes' is not initialized at ../@uirouter/core/lib/params/paramTypes.ts(26,12).
```

Repro:

https://github.com/jonrimmer/quickstart-angular

**Comment by christopherthielen** [comment]
The official way to reference these param types is via `type: 'string'` in your parameter declaration.

This `ParamTypes` class is weird, it has non-initialized static references which are later initialized via `initDefaultTypes()`.  IIRC, I did this because the doc generator did "really bad things" when the references were pre-initialized.  Unfortunately, I don't think we can fix this to work the way you want, and still generate docs from the source code.
