### ISSUE TITLE
Lazy loading - lazy load both a parent state and a child state from the same module

### ISSUE THREAD

**Issue by mtraynham** [ui-router/angular#291]
I have a nav bar, that uses state `data` to properly display icons/handle permissions.  I have a `root.module`, an `app.module`, and subsequent page modules, for this example we'll use one `a.module`.  I'm getting an exception lazy loading the page module state `a.module`, as I wish to basically declaration merge the state providing the `data` up front for it.

The specific exception is:
```
TypeError: Cannot read property 'push' of undefined
    at eval (VM10543 lazyLoadNgModule.js:149)
    at Array.forEach (<anonymous>)
    at applyNgModule (VM10543 lazyLoadNgModule.js:149)
    at applyModule (VM10543 lazyLoadNgModule.js:63)
    at ZoneDelegate.invoke (VM10305 zone.js:387)
    at Object.onInvoke (VM10398 core.js:4981)
    at ZoneDelegate.invoke (VM10305 zone.js:386)
    at Zone.run (VM10305 zone.js:137)
    at eval (VM10305 zone.js:871)
    at ZoneDelegate.invokeTask (VM10305 zone.js:420)
```
or rather [this line of the code base](https://github.com/ui-router/angular/blob/master/src/lazyLoad/lazyLoadNgModule.ts#L196).  It seems as if the `inArray` filter is not removing resolving the child because it didn't find a parent specified (it is also lazy loaded) and therefore `resolvables` is `null`.

### Example
*root.module.ts*
```ts
import {NgModule} from '@angular/core';
import {loadNgModule, UIRouterModule} from '@uirouter/angular';

@NgModule({
    imports: [
        UIRouterModule.forRoot({
            states: [
                {
                    name: 'root',
                    url: '/root'
                },
                {
                    name: 'root.app.**',
                    url: '/app',
                    lazyLoad: loadNgModule(() => import('./app.module')
                        .then((result: any) => result.AppModule))
                }
            ]
        })
    ]
})
export class RootModule { }
```

*app.module.ts*
```ts
import {NgModule} from '@angular/core';
import {loadNgModule, UIRouterModule} from '@uirouter/angular';

@NgModule({
    imports: [
        UIRouterModule.forChild({
            states: [
                {
                    name: 'root.app'
                },
                {
                    name: 'root.app.a.**',
                    url: '/a',
                    lazyLoad: loadNgModule(() => import('./a.module')
                        .then((result: any) => result.AModule))
                },
                {
                    // Lazy loading child state to provide `data`
                    name: 'root.app.a.x.**',
                    url: '/x',
                    data: {
                        foobar: 'Foobar'
                    },
                    lazyLoad: loadNgModule(() => import('./a.module')
                        .then((result: any) => result.AModule))
                }
            ]
        })
    ]
})
export class AppModule { }
```

*a.module.ts*
```ts
import {NgModule} from '@angular/core';
import {UIRouterModule} from '@uirouter/angular';

@NgModule({
    imports: [
        UIRouterModule.forRoot({
            states: [
                {
                    name: 'root.a'
                },
                {
                    name: 'root.a.x'
                    // data: {
                    //     foobar: 'Foobar'
                    // }
                }
            ]
        })
    ]
})
export class AModule { }
```

**Comment by christopherthielen** [comment]
The reason this setup doesn't work the way you want is that future states can't really have children. A future state is supposed to be a placeholder leaf node which is later removed and replaced with the tree of fully defined states.  The idea behind a future state is that the parent module (i.e., `root.app`) can add a wildcard `.**` placeholder *without knowing anything about the states that will be lazy loaded into that placeholder*.  

One fundamental problem with future states is that it can't generate proper hrefs for deep links to the lazy loaded state tree until the definitions are loaded.  Your problem is similar in that you want to use the `data` metadata before the states are fully loaded.

----

> I wish to basically declaration merge the state providing the data up front for it.

Here is an approach which allows you to "merge" eager and lazy portions of your state definitions together.   It avoids the future state mechanism altogether.

For each lazy loaded state, split the state definition into (1) "eager" or "initial" portion and (2) lazy loaded portion like your code is already doing.  The eager portion should contain the minimal amount of information, and should not reference any lazy loaded code/symbols.  The lazy portion of your state definition can *either* re-declare all the eager properties, or it can copy them from the eager definitions.

Here is the stackblitz which demonstrates the approach:  https://stackblitz.com/edit/ui-router-angular-1zl2yw?file=app%2Fapp.module.ts

In this example, the root module `AppModule` imports the `AInitialModule`. 

```ts
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    UIRouterModule.forRoot({
      states: states,
      initial: { state: 'home' },
      config: config
    }),
    AInitialModule, // <--- Registers the initial/eager portion of the states
  ],
  declarations: [GenericComponent, AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Importing `AInitialModule` in turn registers the initial portion of the entire lazy loaded state tree.
The root of the state tree has a `lazyLoad` function which deregisters itself (state `a` and all children), before loading the lazy module.

```ts
export const lazyLoad = (trans: Transition, state: Ng2StateDeclaration) => {
  const loadFn = loadNgModule(() => {
    console.log(`import('./a.lazy.module')`);
    return import('./a.lazy.module').then(esmodule => {
      console.log(`trans.router.stateRegistry.deregister(state.name);`);
      trans.router.stateRegistry.deregister(state.name);
      return esmodule.ALazyModule;
    });
  });

  return loadFn(trans, state);
}

export const states: Ng2StateDeclaration[] = [
  { name: 'a', url: '/a', data: { icon: 'icon-a', }, lazyLoad: lazyLoad },
  { name: 'a.x', url: '/x', data: { icon: 'icon-a-x', } }
]

@NgModule({
  imports: [ UIRouterModule.forChild({ states }) ]
})
export class AInitialModule { }
```

The `ALazyModule` then merges the eager and lazy portions of the state tree.

```ts
import { states as initialStates } from './a.initial.module';

export const lazyStates = [
  {
    name: 'a',
    component: AComponent,
  },
  {
    name: 'a.x',
    component: XComponent,
  }
];

const states = lazyStates.map(lazyState => {
  const { lazyLoad, ...initialState } = initialStates.find(x => x.name === lazyState.name);
  return { ...initialState, ...lazyState };
});

export const config = () => 
  console.log('CONFIGURING A.LAZY MODULE');

@NgModule({
  imports: [
    UIRouterModule.forChild({ states, config }),
  ],
  declarations: [AComponent, XComponent]
})
export class ALazyModule { }
```


I'm closing this as `WONTFIX` because the design of future states really won't allow children.  However, I hope you find this alternative approach useful.  I may even update the lazy loading guide and make this approach the default approach because it provides better `href` support in links.  The downside is having to know information about the lazy loaded children in the parent module(s).

**Comment by mtraynham** [comment]
Awesome, thank you for all this info!
