### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#78]

**Comment by brendanfmartin** [comment]
There's one active maintainer with a recent upgrade.
https://github.com/ui-router/ng2/graphs/contributors
Feel free to find issues and create pull requests if you need updates. Otherwise you can be patient and wait.

**Comment by christopherthielen** [comment]
This project is still active, and I'm committed to maintaining it.  However I have limited resources at the moment, and I am also responsible for maintaining numerous other projects.

I'd like to add new maintainers.  Let me know if anyone is interested.

**Comment by gcca** [comment]
@christopherthielen I interested. Currently I'm working in some issues.

**Comment by christopherthielen** [comment]
@gcca  excellent, thank you.  I'm in the middle of moving out of state, which is why my time is currently so limited.  I'd like to release a new ui-router-core (5.0.0) ASAP once the remaining issues in the milestone are fixed.  Then we can release ui-router-ng2 beta.5 compatible with ng2, and then beta.6 compatible with ng 4+.

I can invite you to the slack we used for ui-router dev communication

**Comment by gcca** [comment]
Great! That will help me to collaborate.

**Comment by christopherthielen** [comment]
@gcca =If you send me your email address, I'll send an invite

email me github at sandgnat dot com

**Comment by wawyed** [comment]
@christopherthielen I would like to help with the project if it's possible.

**Comment by christopherthielen** [comment]
Please send me your email addresses @gcca @wawyed and I'll invite you to the slack.

**Comment by christopherthielen** [comment]
I'm `@christhielen` on twitter

**Comment by wawyed** [comment]
Cool, email sent.
